### ISSUE TITLE
Installation VLC and pyqt5

### ISSUE THREAD

**Issue by freaad** [UAVs-at-Berkeley/flywave#1]
I see that you guys use the VLC and pyqt5.
Could you guide that how to install the VLC python and pyqt5?
I am using the anaconda virtual -env in windows 10. 
I ask the amy who made pyparrot but he is busy looks like. 
Could you help me 
Thanks

**Comment by alexc2684** [comment]
What problems are you running into? I don't remember the installation process exactly but I can try my best if you show me the error.

**Comment by alexc2684** [comment]
Try running 
```
pip install python-vlc
```
And try a normal pip install for pyqt5. Let me know if this works for you.

**Comment by freaad** [comment]
Thanks it works. 
I have extra question that do you guys solve the vlc delay issue? I have noticeable delay. I change the network cache as 200. It reduces the noise but it still has the delay.

**Comment by alexc2684** [comment]
I don't get any delay when using VLC. If you're using DroneVisionGUI, it shouldn't be a problem.

**Comment by freaad** [comment]
I read your code about object tracking. Actually it use the drone vision and it saves the image very well.
However I want to see the video during the flight. 

movie=path+'\utils\bebop.sdp'#path
player=vlc.MediaPlayer(movie)
player.play()
This is what I tried and I can see the video but it has certain delay.

**Comment by alexc2684** [comment]
The object tracking has considerable delay. I assume it is because of the frame buffer that is used to feed into the model. We ended up using a keras model instead and pulled every 10-20 frames rather than every frame. This reduced the lag we were seeing in the object tracking code.

**Comment by freaad** [comment]
Makes sense So you are using the some frames for control.
Thanks.

**Comment by alexc2684** [comment]
No problem! Marking this issue as resolved.
